### PR TITLE
cscope: rewrite function: db_build

### PR DESCRIPTION
**Pull request by Zefrain**
1. if Makefile exists: try `make cscope`
    2. if .git exists: run `git ls-files | cscope ${db_build_cmd_args} -i -`
    3. if all fails: run `find . -name '*.c' -o -name '*.cpp' -o -name '*.h' | cscope ${db_build_cmd_args} -i -`

### CODE REVIEW

**Comment by Zefrain** [comment]
because it always tells me no source files found, so I rewrite db_build to build the database. I'm not sure whether it is a better choice.

**Comment by dhananjaylatkar** [comment]
You might want to add "-R" in db_build_cmd_args

**Comment by Zefrain** [comment]
> You might want to add "-R" in db_build_cmd_args

the args are ok, I closed it because I have tried build a project in docker, so `make cscope` runs failed in host, but the next command didn't run, I think I may need to do some extra works

**Comment by Zefrain** [comment]
> > You might want to add "-R" in db_build_cmd_args
> 
> the args are ok, I closed it because I have tried to build a project in docker, so `make cscope` runs failed in host, but the next command didn't run, I think I may need to do some extra works

I use -v to mount the project directory,  they have different path

**Pull request closed without merging**
